#!/bin/sh
set -eu

log() {
    echo "install-kubectl: $1" >&2
}

check_sha256() {
    if ! echo "$2 $1" | sha256sum --check; then
        log "Failed to verify: hash mismatch: filename=$1, expected=$2, actual=$(sha256sum "$1" | awk '{ print $1 }')"
        exit 1
    fi
}

if [ $# -ne 2 ]; then
    echo "Usage: $(basename "$0") VERSION SHA256" >&2
    exit 2
fi

VERSION="$1"
SHA256="$2"

log "VERSION: $VERSION"

TOP_DIR=$(git rev-parse --show-toplevel)
TOOLS_DIR="$TOP_DIR/tools"
KUBECTL_DIR="$TOOLS_DIR/kubectl-$VERSION"
KUBECTL_PATH="${KUBECTL_DIR}/kubectl"

mkdir -p "$KUBECTL_DIR"
log "Download kubectl..."
curl -sfL -o "${KUBECTL_PATH}" https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl
check_sha256 "${KUBECTL_PATH}" "$SHA256"

chmod a+x "${KUBECTL_PATH}"

log "Installed"
